const router = require('express').Router();
const controller = require('../controllers/webController');
const { requireAuth, requireVerified } = require('../middleware/auth');
const settingsController = require('../controllers/settingsController');
const communityController = require('../controllers/communityController');
const { postUpload, profileUpload, communityUpload, reportUpload, groupUpload, chatAttachmentUpload, validateChatAttachment, validateGroupUpload, validatePostUpload, validateProfileUpload, validateCommunityUpload, validateReportUpload, scanUploadsForViruses, handleUploadError } = require('../middleware/uploads');
const interactionController = require('../controllers/interactionController');
const groupController = require('../controllers/groupController');
const { interactionLimiter, apiLimiter, pollLimiter, messageSearchLimiter, gifLimiter, translateLimiter, csrfSynchronisedProtection } = require('../middleware/security');
const chatController = require('../controllers/chatController');
const shareController = require('../controllers/shareController');
const gifController = require('../controllers/gifController');
const twoFactorController = require('../controllers/twoFactorController');
const appealController = require('../controllers/appealController');
const adminController = require('../controllers/adminController');
const translateController = require('../controllers/translateController');
const wavesController = require('../controllers/wavesController');
const advertisingController = require('../controllers/advertisingController');
const { requireAdmin, requireModerator, requirePanelPassword } = require('../middleware/roles');

router.get('/', controller.home);
router.get('/health', controller.health);
router.get('/rss.xml', controller.rss);
router.get('/u/:id/rss.xml', controller.profileRss);
router.get('/api/v1/posts', apiLimiter, controller.apiPosts);
router.get('/dashboard', requireAuth, requireVerified, controller.dashboard);
router.get('/wallet', requireAuth, requireVerified, wavesController.wallet);
router.post('/wallet/transfer', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, wavesController.transfer);
router.get('/advertising', requireAuth, requireVerified, advertisingController.dashboard);
router.post('/advertising/accept-terms', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.acceptTerms);
router.post('/advertising/apply', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.apply);
router.post('/advertising/appeal', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.submitAdvertiserAppeal);
router.post('/advertising/campaigns', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.createCampaign);
router.post('/advertising/campaigns/:id/action', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.campaignAction);
router.post('/ads/:id/impression', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.trackCampaignImpression);
router.get('/ads/:id/click', requireAuth, requireVerified, interactionLimiter, advertisingController.clickCampaign);
router.post('/ads/:id/report', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, advertisingController.reportCampaign);
router.get('/recap', requireAuth, requireVerified, controller.activityRecap);
router.get('/dashboard/feed/more', requireAuth, requireVerified, controller.moreFeedPosts);
router.get('/media/signed-upload', requireAuth, requireVerified, controller.signedUpload);
router.get('/media/status', requireAuth, requireVerified, controller.mediaStatus);
router.get('/media/:cluster/:id', controller.media);
router.get('/notifications', requireAuth, requireVerified, interactionController.notifications);
router.get('/notifications/unread', requireAuth, requireVerified, interactionController.unreadCount);
router.get('/messages', requireAuth, requireVerified, interactionController.messages);
router.get('/messages/requests', requireAuth, requireVerified, interactionController.messageRequests);
router.get('/messages/:id/search', requireAuth, requireVerified, messageSearchLimiter, chatController.dmSearch);
router.get('/messages/:id', requireAuth, requireVerified, chatController.dmThread);
router.get('/messages/:id/poll', requireAuth, requireVerified, pollLimiter, chatController.dmPoll);
router.get('/messages/:id/history', requireAuth, requireVerified, pollLimiter, chatController.dmHistory);
router.get('/messages/:id/:messageId/attachment', requireAuth, requireVerified, chatController.dmAttachment);
router.post('/messages/:id/:messageId/report', requireAuth, requireVerified, interactionLimiter, chatController.dmReportMessage);
router.post('/messages/:id', requireAuth, requireVerified, interactionLimiter, chatAttachmentUpload, csrfSynchronisedProtection, handleUploadError, validateChatAttachment, scanUploadsForViruses, chatController.dmSend);
router.post('/messages/:id/delete', requireAuth, requireVerified, interactionLimiter, chatController.dmDeleteMessages);
router.post('/messages/requests/:id/respond', requireAuth, requireVerified, interactionLimiter, chatController.dmRequestRespond);
router.post('/messages/:id/react', requireAuth, requireVerified, interactionLimiter, chatController.dmReact);
router.get('/groups', requireAuth, requireVerified, groupController.list);
router.post('/groups', requireAuth, requireVerified, interactionLimiter, groupController.create);
router.get('/groups/join/:code', requireAuth, requireVerified, groupController.joinPreview);
router.post('/groups/join/:code', requireAuth, requireVerified, interactionLimiter, groupController.joinConfirm);
router.get('/groups/:id/search', requireAuth, requireVerified, messageSearchLimiter, chatController.groupSearch);
router.get('/groups/:id', requireAuth, requireVerified, chatController.groupThread);
router.get('/groups/:id/poll', requireAuth, requireVerified, pollLimiter, chatController.groupPoll);
router.get('/groups/:id/history', requireAuth, requireVerified, pollLimiter, chatController.groupHistory);
router.get('/groups/:id/messages/:messageId/attachment', requireAuth, requireVerified, chatController.groupAttachment);
router.post('/groups/:id/messages/:messageId/report', requireAuth, requireVerified, interactionLimiter, chatController.groupReportMessage);
router.post('/groups/:id', requireAuth, requireVerified, interactionLimiter, chatAttachmentUpload, csrfSynchronisedProtection, handleUploadError, validateChatAttachment, scanUploadsForViruses, chatController.groupSend);
router.post('/groups/:id/messages/delete', requireAuth, requireVerified, interactionLimiter, chatController.groupDeleteMessages);
router.post('/groups/:id/messages/:messageId/react', requireAuth, requireVerified, interactionLimiter, chatController.groupReact);
router.get('/groups/:id/info', requireAuth, requireVerified, groupController.info);
router.post('/groups/:id/rename', requireAuth, requireVerified, interactionLimiter, groupController.rename);
router.post('/groups/:id/avatar', requireAuth, requireVerified, interactionLimiter, groupUpload, csrfSynchronisedProtection, handleUploadError, validateGroupUpload, scanUploadsForViruses, groupController.setAvatar);
router.post('/groups/:id/avatar/remove', requireAuth, requireVerified, interactionLimiter, groupController.removeAvatar);
router.post('/groups/:id/members', requireAuth, requireVerified, interactionLimiter, groupController.addMembers);
router.post('/groups/:id/members/:userId/remove', requireAuth, requireVerified, interactionLimiter, groupController.removeMember);
router.post('/groups/:id/members/:userId/admin', requireAuth, requireVerified, interactionLimiter, groupController.toggleAdmin);
router.post('/groups/:id/leave', requireAuth, requireVerified, interactionLimiter, groupController.leave);
router.post('/groups/:id/invite', requireAuth, requireVerified, interactionLimiter, groupController.createInvite);
router.post('/groups/:id/invite/revoke', requireAuth, requireVerified, interactionLimiter, groupController.revokeInvite);
router.get('/gifs/search', requireAuth, requireVerified, gifLimiter, gifController.search);
router.get('/share/targets', requireAuth, requireVerified, pollLimiter, shareController.targets);
router.post('/posts/:id/share/send', requireAuth, requireVerified, interactionLimiter, shareController.send);
router.get('/posts', controller.publicPosts);
router.get('/posts/:id/edit', requireAuth, requireVerified, interactionController.editPostPage);
router.get('/posts/:id/reply', requireAuth, requireVerified, interactionController.replyPostPage);
router.get('/posts/:id', interactionController.postDetail);
router.post('/posts/:id/edit', requireAuth, requireVerified, interactionLimiter, interactionController.editPost);
router.post('/posts/:id/promote', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, interactionController.promotePost);
router.post('/posts/:id/delete', requireAuth, requireVerified, interactionLimiter, interactionController.deletePost);
router.post('/posts/:id/moderate', requireAuth, requireVerified, requireModerator, adminController.moderatePost);
router.get('/posts/:id/comments', interactionController.commentThread);
router.post('/notifications/read', requireAuth, requireVerified, interactionController.readNotifications);
router.post('/posts/:id/like', requireAuth, requireVerified, interactionLimiter, interactionController.toggleLike);
router.post('/posts/:id/report', requireAuth, requireVerified, interactionLimiter, reportUpload, csrfSynchronisedProtection, handleUploadError, validateReportUpload, scanUploadsForViruses, interactionController.reportPost);
router.post('/comments/:id/report', requireAuth, requireVerified, interactionLimiter, interactionController.reportComment);
router.post('/posts/:id/comments', requireAuth, requireVerified, interactionLimiter, interactionController.comment);
router.post('/comments/:id/edit', requireAuth, requireVerified, interactionLimiter, interactionController.editComment);
router.post('/comments/:id/delete', requireAuth, requireVerified, interactionLimiter, interactionController.deleteComment);
router.post('/comments/:id/like', requireAuth, requireVerified, interactionLimiter, interactionController.toggleCommentLike);
router.post('/comments/:id/author-heart', requireAuth, requireVerified, interactionLimiter, interactionController.toggleAuthorHeart);
router.post('/comments/:id/react', requireAuth, requireVerified, interactionLimiter, interactionController.toggleCommentReaction);
router.post('/posts/:id/bookmark', requireAuth, requireVerified, interactionLimiter, interactionController.toggleBookmark);
router.post('/posts/:id/share', requireAuth, requireVerified, interactionLimiter, interactionController.share);
router.post('/posts/:id/poll/vote', requireAuth, requireVerified, interactionLimiter, interactionController.votePoll);
router.post('/posts/:id/reaction', requireAuth, requireVerified, interactionLimiter, interactionController.toggleReaction);
router.post('/posts/:id/reply', requireAuth, requireVerified, postUpload, csrfSynchronisedProtection, handleUploadError, validatePostUpload, scanUploadsForViruses, interactionLimiter, interactionController.replyPost);
router.get('/translate/languages', requireAuth, requireVerified, translateController.languages);
router.post('/translate', requireAuth, requireVerified, translateLimiter, translateController.translate);
router.get('/community-map', requireAuth, requireVerified, communityController.communityMap);
router.get('/explore', requireAuth, requireVerified, communityController.explore);
router.get('/people', requireAuth, requireVerified, communityController.peopleToFollow);
router.get('/communities', requireAuth, requireVerified, communityController.directory);
router.get('/communities/mine', requireAuth, requireVerified, communityController.mine);
router.get('/communities/rising', requireAuth, requireVerified, communityController.risingCommunities);
router.get('/search', requireAuth, requireVerified, controller.search);
router.post('/search/history/clear', requireAuth, requireVerified, controller.clearSearchHistory);
router.get('/hashtags/suggest', requireAuth, requireVerified, controller.hashtagSuggestions);
router.get('/users/suggest', requireAuth, requireVerified, controller.userSuggestions);
router.get('/u/:id', requireAuth, requireVerified, controller.profile);
router.post('/users/:id/follow', requireAuth, requireVerified, interactionLimiter, interactionController.toggleFollow);
router.post('/users/:id/block', requireAuth, requireVerified, interactionLimiter, interactionController.toggleBlock);
router.post('/users/:id/mute', requireAuth, requireVerified, interactionLimiter, interactionController.toggleMute);
router.get('/u/:id/followers', requireAuth, requireVerified, controller.followersPage);
router.get('/u/:id/following', requireAuth, requireVerified, controller.followingPage);
router.get('/communities/:slug/rss.xml', controller.communityRss);
router.get('/communities/invite/:code', requireAuth, requireVerified, communityController.invitePreview);
router.post('/communities/invite/:code/join', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.joinByInvite);
router.get('/communities/:slug', requireAuth, requireVerified, communityController.detail);
router.post('/posts', requireAuth, requireVerified, postUpload, csrfSynchronisedProtection, handleUploadError, validatePostUpload, scanUploadsForViruses, controller.createPost);
router.post('/communities', requireAuth, requireVerified, controller.createCommunity);
router.post('/communities/:id/join', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.requestJoin);
router.post('/communities/:id/leave', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.leaveCommunity);
router.post('/communities/:id/join-request/cancel', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.cancelJoinRequest);
router.post('/communities/:id/quests', requireAuth, requireVerified, communityController.moderationOnly, communityController.createQuest);
router.post('/communities/:id/quests/:questId/join', requireAuth, requireVerified, communityController.loadCommunity, communityController.toggleQuestParticipation);
router.post('/communities/:id/quests/:questId/complete', requireAuth, requireVerified, communityController.loadCommunity, communityController.completeQuest);
router.post('/communities/:id/quests/:questId/end', requireAuth, requireVerified, communityController.moderationOnly, communityController.endQuest);
router.post('/communities/:id/quests/:questId/reward', requireAuth, requireVerified, communityController.moderationOnly, communityController.rewardQuestWinner);
router.get('/communities/:id/manage', requireAuth, requireVerified, communityController.ownerOnly, communityController.manage);
router.post('/communities/:id/invite', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.ownerOnly, communityController.createInvite);
router.post('/communities/:id/invite/revoke', requireAuth, requireVerified, csrfSynchronisedProtection, communityController.ownerOnly, communityController.revokeInvite);
router.post('/communities/:id/promote', requireAuth, requireVerified, interactionLimiter, csrfSynchronisedProtection, communityController.ownerOnly, communityController.promoteCommunity);
router.post('/communities/:id/monetization', requireAuth, requireVerified, communityController.ownerOnly, interactionLimiter, csrfSynchronisedProtection, communityController.submitMonetizationApplication);
router.post('/communities/:id/monetization/appeal', requireAuth, requireVerified, communityController.ownerOnly, interactionLimiter, csrfSynchronisedProtection, communityController.submitMonetizationAppeal);
router.post('/communities/:id/manage', requireAuth, requireVerified, communityController.ownerOnly, communityUpload, csrfSynchronisedProtection, handleUploadError, validateCommunityUpload, scanUploadsForViruses, communityController.update);
router.post('/communities/:id/moderators', requireAuth, requireVerified, communityController.ownerOnly, communityController.addModerator);
router.post('/communities/:id/posts/:postId/review', requireAuth, requireVerified, communityController.moderationOnly, communityController.reviewPost);
router.post('/communities/:id/posts/:postId/pin', requireAuth, requireVerified, communityController.moderationOnly, communityController.togglePinPost);
router.post('/communities/:id/members/:memberId/remove', requireAuth, requireVerified, communityController.ownerOnly, communityController.removeMember);
router.post('/communities/:id/requests/:userId', requireAuth, requireVerified, communityController.moderationOnly, communityController.reviewRequest);
router.post('/communities/:id/members/:userId/role', requireAuth, requireVerified, communityController.ownerOnly, communityController.setModerator);
router.get('/:panel(admin|moderator)/access', requireAuth, requireVerified, adminController.panelAccessPage);
router.post('/:panel(admin|moderator)/access', requireAuth, requireVerified, adminController.panelAccess);
router.get('/admin', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.admin);
router.post('/admin/moderators', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.createModerator);
router.post('/admin/moderators/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteModerator);
router.post('/admin/reports/:id', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.resolveReport);
router.post('/admin/appeals/:id', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.resolveAppeal);
router.post('/admin/moderation/:id/review', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.reviewAction);
router.post('/admin/posts/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deletePost);
router.post('/admin/posts/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updatePost);
router.post('/admin/users/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteUser);
router.post('/admin/users/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateUser);
router.post('/admin/communities/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateCommunity);
router.post('/admin/communities/:id/monetization', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), csrfSynchronisedProtection, adminController.reviewMonetization);
router.post('/admin/ad-abuse/:id/review', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), csrfSynchronisedProtection, adminController.reviewAdAbuseSignal);
router.post('/moderator/communities/:id/monetization', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), csrfSynchronisedProtection, adminController.reviewCommunityMonetizationAsModerator);
router.post('/admin/advertisers/:id/review', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), csrfSynchronisedProtection, adminController.reviewAdvertiser);
router.post('/moderator/advertisers/:id/review', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), csrfSynchronisedProtection, adminController.reviewAdvertiserAsModerator);
router.post('/admin/campaigns/:id/review', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), csrfSynchronisedProtection, adminController.reviewCampaign);
router.post('/admin/campaigns/:id/manage', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), csrfSynchronisedProtection, adminController.manageCampaign);
router.post('/admin/communities/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteCommunity);
router.post('/admin/settings', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateSiteSettings);
router.post('/admin/maintenance/run', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.runMaintenance);
router.get('/moderator', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), adminController.moderator);
router.post('/moderator/actions', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), adminController.submitAction);
router.post('/moderator/campaigns/:id/review', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), csrfSynchronisedProtection, adminController.reviewCampaignAsModerator);
router.post('/moderator/appeals/:id', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), adminController.resolveAppeal);
router.get('/settings/:section?', requireAuth, requireVerified, settingsController.page);
router.post('/settings/profile', requireAuth, requireVerified, profileUpload, csrfSynchronisedProtection, handleUploadError, validateProfileUpload, scanUploadsForViruses, settingsController.updateProfile);
router.post('/settings/security/password', requireAuth, requireVerified, settingsController.changePassword);
router.get('/settings/security/2fa', requireAuth, requireVerified, twoFactorController.setupPage);
router.post('/settings/security/2fa', requireAuth, requireVerified, twoFactorController.enable);
router.get('/settings/security/2fa/recovery-codes', requireAuth, requireVerified, twoFactorController.recoveryCodesPage);
router.post('/settings/security/2fa/recovery-codes/regenerate', requireAuth, requireVerified, twoFactorController.regenerateRecoveryCodes);
router.post('/settings/security/2fa/disable', requireAuth, requireVerified, twoFactorController.disable);
router.post('/settings/security/devices/:id/logout', requireAuth, requireVerified, settingsController.logoutDevice);
router.post('/settings/security/devices/logout-all', requireAuth, requireVerified, settingsController.logoutAll);
router.post('/settings/privacy', requireAuth, requireVerified, settingsController.setInactivity);
router.post('/settings/notifications', requireAuth, requireVerified, settingsController.setNotifications);
router.post('/settings/theme', requireAuth, requireVerified, settingsController.setTheme);
router.post('/settings/appeals', requireAuth, requireVerified, appealController.submitAppeal);
router.get('/settings/push/public-key', requireAuth, requireVerified, settingsController.pushPublicKey);
router.post('/settings/push/subscribe', requireAuth, requireVerified, settingsController.pushSubscribe);
router.post('/settings/push/unsubscribe', requireAuth, requireVerified, settingsController.pushUnsubscribe);
router.get('/settings/account/download', requireAuth, requireVerified, settingsController.downloadData);
router.post('/settings/account/delete', requireAuth, requireVerified, settingsController.deleteAccount);
router.get('/guide', controller.guide);
router.get('/docs', controller.docs);
['/about', '/about/developer', '/privacy', '/terms', '/advertising/terms', '/waves/terms', '/community-monetization/terms', '/community-guidelines', '/accessibility', '/contact', '/help'].forEach((path) => router.get(path, controller.infoPage));
router.get('/robots.txt', controller.robots);
router.get('/sitemap.xml', controller.sitemap);

module.exports = router;
