const router = require('express').Router();
const controller = require('../controllers/webController');
const { requireAuth, requireVerified } = require('../middleware/auth');
const settingsController = require('../controllers/settingsController');
const communityController = require('../controllers/communityController');
const { postUpload, profileUpload, communityUpload, validatePostUpload, validateProfileUpload, validateCommunityUpload, handleUploadError } = require('../middleware/uploads');
const interactionController = require('../controllers/interactionController');
const groupController = require('../controllers/groupController');
const { interactionLimiter, apiLimiter, csrfSynchronisedProtection } = require('../middleware/security');
const twoFactorController = require('../controllers/twoFactorController');
const adminController = require('../controllers/adminController');
const { requireAdmin, requireModerator, requirePanelPassword } = require('../middleware/roles');

router.get('/', controller.home);
router.get('/health', controller.health);
router.get('/rss.xml', controller.rss);
router.get('/api/v1/posts', apiLimiter, controller.apiPosts);
router.get('/dashboard', requireAuth, requireVerified, controller.dashboard);
router.get('/dashboard/feed/more', requireAuth, requireVerified, controller.moreFeedPosts);
router.get('/media/signed-upload', requireAuth, requireVerified, controller.signedUpload);
router.get('/media/status', requireAuth, requireVerified, controller.mediaStatus);
router.get('/media/:cluster/:id', controller.media);
router.get('/notifications', requireAuth, requireVerified, interactionController.notifications);
router.get('/notifications/unread', requireAuth, requireVerified, interactionController.unreadCount);
router.get('/messages', requireAuth, requireVerified, interactionController.messages);
router.get('/messages/:id', requireAuth, requireVerified, interactionController.messageThread);
router.post('/messages/:id', requireAuth, requireVerified, interactionLimiter, interactionController.sendMessage);
router.get('/groups', requireAuth, requireVerified, groupController.list);
router.post('/groups', requireAuth, requireVerified, interactionLimiter, groupController.create);
router.get('/groups/:id', requireAuth, requireVerified, groupController.thread);
router.post('/groups/:id', requireAuth, requireVerified, interactionLimiter, groupController.send);
router.get('/posts/:id', interactionController.postDetail);
router.post('/posts/:id/edit', requireAuth, requireVerified, interactionLimiter, interactionController.editPost);
router.post('/posts/:id/delete', requireAuth, requireVerified, interactionLimiter, interactionController.deletePost);
router.post('/posts/:id/moderate', requireAuth, requireVerified, requireModerator, adminController.moderatePost);
router.get('/posts/:id/comments', interactionController.commentThread);
router.post('/notifications/read', requireAuth, requireVerified, interactionController.readNotifications);
router.post('/posts/:id/like', requireAuth, requireVerified, interactionLimiter, interactionController.toggleLike);
router.post('/posts/:id/report', requireAuth, requireVerified, interactionLimiter, interactionController.reportPost);
router.post('/posts/:id/comments', requireAuth, requireVerified, interactionLimiter, interactionController.comment);
router.post('/comments/:id/edit', requireAuth, requireVerified, interactionLimiter, interactionController.editComment);
router.post('/comments/:id/delete', requireAuth, requireVerified, interactionLimiter, interactionController.deleteComment);
router.post('/comments/:id/like', requireAuth, requireVerified, interactionLimiter, interactionController.toggleCommentLike);
router.post('/posts/:id/bookmark', requireAuth, requireVerified, interactionLimiter, interactionController.toggleBookmark);
router.post('/posts/:id/share', requireAuth, requireVerified, interactionLimiter, interactionController.share);
router.post('/posts/:id/poll/vote', requireAuth, requireVerified, interactionLimiter, interactionController.votePoll);
router.post('/posts/:id/quote', requireAuth, requireVerified, interactionLimiter, interactionController.quotePost);
router.post('/posts/:id/reaction', requireAuth, requireVerified, interactionLimiter, interactionController.toggleReaction);
router.post('/posts/:id/reply', requireAuth, requireVerified, interactionLimiter, interactionController.replyPost);
router.get('/explore', requireAuth, requireVerified, communityController.explore);
router.get('/communities', requireAuth, requireVerified, communityController.directory);
router.get('/search', requireAuth, requireVerified, controller.search);
router.get('/hashtags/suggest', requireAuth, requireVerified, controller.hashtagSuggestions);
router.get('/users/suggest', requireAuth, requireVerified, controller.userSuggestions);
router.get('/u/:id', requireAuth, requireVerified, controller.profile);
router.post('/users/:id/follow', requireAuth, requireVerified, interactionLimiter, interactionController.toggleFollow);
router.post('/users/:id/block', requireAuth, requireVerified, interactionLimiter, interactionController.toggleBlock);
router.post('/users/:id/mute', requireAuth, requireVerified, interactionLimiter, interactionController.toggleMute);
router.get('/u/:id/followers', requireAuth, requireVerified, controller.followersPage);
router.get('/u/:id/following', requireAuth, requireVerified, controller.followingPage);
router.get('/communities/:slug', requireAuth, requireVerified, communityController.detail);
router.post('/posts', requireAuth, requireVerified, postUpload, csrfSynchronisedProtection, handleUploadError, validatePostUpload, controller.createPost);
router.post('/communities', requireAuth, requireVerified, controller.createCommunity);
router.post('/communities/:id/join', requireAuth, requireVerified, communityController.requestJoin);
router.get('/communities/:id/manage', requireAuth, requireVerified, communityController.ownerOnly, communityController.manage);
router.post('/communities/:id/manage', requireAuth, requireVerified, communityController.ownerOnly, communityUpload, csrfSynchronisedProtection, handleUploadError, validateCommunityUpload, communityController.update);
router.post('/communities/:id/moderators', requireAuth, requireVerified, communityController.ownerOnly, communityController.addModerator);
router.post('/communities/:id/posts/:postId/review', requireAuth, requireVerified, communityController.moderationOnly, communityController.reviewPost);
router.post('/communities/:id/posts/:postId/pin', requireAuth, requireVerified, communityController.moderationOnly, communityController.togglePinPost);
router.post('/communities/:id/members/:memberId/remove', requireAuth, requireVerified, communityController.ownerOnly, communityController.removeMember);
router.post('/communities/:id/requests/:userId', requireAuth, requireVerified, communityController.moderationOnly, communityController.reviewRequest);
router.post('/communities/:id/members/:userId/role', requireAuth, requireVerified, communityController.ownerOnly, communityController.setModerator);
router.get('/:panel(admin|moderator)/access', requireAuth, requireVerified, adminController.panelAccessPage);
router.post('/:panel(admin|moderator)/access', requireAuth, requireVerified, adminController.panelAccess);
router.get('/admin', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.admin);
router.post('/admin/moderators', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.createModerator);
router.post('/admin/moderators/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteModerator);
router.post('/admin/reports/:id', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.resolveReport);
router.post('/admin/moderation/:id/review', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.reviewAction);
router.post('/admin/posts/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deletePost);
router.post('/admin/posts/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updatePost);
router.post('/admin/users/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteUser);
router.post('/admin/users/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateUser);
router.post('/admin/communities/:id/edit', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateCommunity);
router.post('/admin/communities/:id/delete', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.deleteCommunity);
router.post('/admin/settings', requireAuth, requireVerified, requireAdmin, requirePanelPassword('admin'), adminController.updateSiteSettings);
router.get('/moderator', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), adminController.moderator);
router.post('/moderator/actions', requireAuth, requireVerified, requireModerator, requirePanelPassword('moderator'), adminController.submitAction);
router.get('/settings/:section?', requireAuth, requireVerified, settingsController.page);
router.post('/settings/profile', requireAuth, requireVerified, profileUpload, csrfSynchronisedProtection, handleUploadError, validateProfileUpload, settingsController.updateProfile);
router.post('/settings/security/password', requireAuth, requireVerified, settingsController.changePassword);
router.get('/settings/security/2fa', requireAuth, requireVerified, twoFactorController.setupPage);
router.post('/settings/security/2fa', requireAuth, requireVerified, twoFactorController.enable);
router.get('/settings/security/2fa/recovery-codes', requireAuth, requireVerified, twoFactorController.recoveryCodesPage);
router.post('/settings/security/2fa/recovery-codes/regenerate', requireAuth, requireVerified, twoFactorController.regenerateRecoveryCodes);
router.post('/settings/security/2fa/disable', requireAuth, requireVerified, twoFactorController.disable);
router.post('/settings/security/devices/:id/logout', requireAuth, requireVerified, settingsController.logoutDevice);
router.post('/settings/security/devices/logout-all', requireAuth, requireVerified, settingsController.logoutAll);
router.post('/settings/privacy', requireAuth, requireVerified, settingsController.setInactivity);
router.post('/settings/notifications', requireAuth, requireVerified, settingsController.setNotifications);
router.get('/settings/account/download', requireAuth, requireVerified, settingsController.downloadData);
router.post('/settings/account/delete', requireAuth, requireVerified, settingsController.deleteAccount);
router.get('/guide', controller.guide);
['/about', '/about/developer', '/privacy', '/terms', '/community-guidelines', '/accessibility', '/contact'].forEach((path) => router.get(path, controller.infoPage));
router.get('/robots.txt', controller.robots);
router.get('/sitemap.xml', controller.sitemap);

module.exports = router;
